name: ubuntu-image
summary: Create Ubuntu images
description: |
  Official tool for building Ubuntu images, currently supporing Ubuntu Core
  snap-based images and preinstalled Ubuntu classic images.
version: 2.1+snap5
grade: stable
confinement: classic
base: core20

# Force the snap to only use binaries staged with the snap
environment:
  PATH: $SNAP/usr/local/sbin:$SNAP/usr/bin:$SNAP/bin:$SNAP/sbin:$SNAP/usr/local/bin:$SNAP/usr/sbin
  FAKEROOT_LIB: $SNAP/usr/lib/lib-arch/libfakeroot/libfakeroot-tcp.so

apps:
  ubuntu-image:
    command: bin/ubuntu-image

parts:
  ubuntu-image:
    plugin: go
    source: .
    source-type: git
    build-packages:
      - golang-go
      - fdisk
      - gdisk
      - mtools
      - python3-docutils
    stage-packages:
      - mtools
      - fdisk
      - gdisk
      - e2fsprogs
      - fakeroot
      - dosfstools
      - squashfs-tools
      - coreutils
      - util-linux
      - sed
    override-build: |
      snapcraftctl build
      # create a symlink /usr/bin/fakeroot -> /usr/bin/fakeroot-tcp
      cd $SNAPCRAFT_PART_INSTALL/usr/bin/
      ln -s fakeroot-tcp fakeroot
      # Create a symbolic link to /usr/lib/<arch> where libfakeroot will live
      cd $SNAPCRAFT_PART_INSTALL/usr/lib/
      ln -s *-linux-gnu* lib-arch
