name: ubuntu-image
summary: Create Ubuntu images
description: |
  Official tool for building Ubuntu images, currently supporing Ubuntu Core
  snap-based images and preinstalled Ubuntu classic images.
version: 2.2+snap8
grade: stable
confinement: classic
base: core20
source-code: https://github.com/canonical/ubuntu-image
issues: https://bugs.launchpad.net/ubuntu-image/+filebug

# Force the snap to use fakeroot staged within the snap
environment:
  FAKEROOT_FLAGS: "--lib $SNAP/usr/lib/lib-arch/libfakeroot/libfakeroot-tcp.so --faked $SNAP/usr/bin/faked-tcp"
  PATH: $SNAP/usr/bin:$SNAP/bin:$SNAP/sbin:$PATH

apps:
  ubuntu-image:
    command: bin/ubuntu-image

parts:
  ubuntu-image:
    plugin: go
    source: .
    source-type: git
    build-packages:
      - golang-go
      - fdisk
      - gdisk
      - mtools
      - python3-docutils
    stage-packages:
      - mtools
      - fdisk
      - gdisk
      - e2fsprogs
      - fakeroot
      - dosfstools
      - squashfs-tools
    override-build: |
      snapcraftctl build
      # create a symlink /usr/bin/fakeroot -> /usr/bin/fakeroot-tcp
      cd $SNAPCRAFT_PART_INSTALL/usr/bin/
      ln -s fakeroot-tcp fakeroot
      # Create a symbolic link to /usr/lib/<arch> where libfakeroot will live
      cd $SNAPCRAFT_PART_INSTALL/usr/lib/
      ln -s ${SNAPCRAFT_ARCH_TRIPLET} lib-arch
