name: Dependencies vulnerability check

on: [pull_request]

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: 1.18
           go-package: ./...
